# Generated by Django 6.0.4 on 2026-04-27 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الموبايل')),
                ('car_info', models.CharField(max_length=100, verbose_name='معلومات سيارة السائق')),
                ('is_active', models.BooleanField(default=True, verbose_name='هل السائق يعمل حالياً؟')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب السائق')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('car_model', models.CharField(max_length=100, verbose_name='نوع السيارة')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الموبايل')),
                ('service_type', models.CharField(max_length=100, verbose_name='نوع الخدمة')),
                ('area', models.CharField(blank=True, default='عمان', max_length=100, null=True, verbose_name='المنطقة')),
                ('appointment_time', models.DateTimeField(verbose_name='وقت الاستلام')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'تم القبول - السائق في الطريق'), ('in_progress', 'جاري العمل على السيارة'), ('completed', 'تم التسليم بنجاح'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('driver_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driver', verbose_name='السائق المسؤول')),
            ],
        ),
    ]
