# Generated by Django 5.2.13 on 2026-04-30 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car_info',
        ),
        migrations.AddField(
            model_name='driver',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الموافقة'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_color',
            field=models.CharField(default='', max_length=50, verbose_name='لون السيارة'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_model',
            field=models.CharField(default='', max_length=100, verbose_name='موديل السيارة'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_year',
            field=models.CharField(default='', max_length=4, verbose_name='سنة الصنع'),
        ),
        migrations.AddField(
            model_name='driver',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/faces/', verbose_name='صورة الوجه'),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/ids/', verbose_name='صورة الهوية - الظهر'),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/ids/', verbose_name='صورة الهوية - الوجه'),
        ),
        migrations.AddField(
            model_name='driver',
            name='lat',
            field=models.FloatField(default=31.95, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/licenses/', verbose_name='رخصة القيادة'),
        ),
        migrations.AddField(
            model_name='driver',
            name='lon',
            field=models.FloatField(default=35.91, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_license',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/vehicle_licenses/', verbose_name='رخصة السيارة'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer_lat',
            field=models.FloatField(default=31.95, verbose_name='خط عرض العميل'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer_lon',
            field=models.FloatField(default=35.91, verbose_name='خط طول العميل'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('qliq', 'QLIQ')], default='cash', max_length=10, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الموعد'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='متصل حالياً'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='appointment_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_type',
            field=models.CharField(choices=[('body_wash', 'غسيل خارجي'), ('full_wash', 'غسيل كامل'), ('dry_clean', 'دراي كلين'), ('oil_change', 'غيّار زيت'), ('oil_filter', 'غيّار زيت وفلتر')], default='body_wash', max_length=20, verbose_name='نوع الخدمة'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'تم القبول - السائق في الطريق'), ('arrived', 'السائق وصل'), ('picking_up', 'جاري استلام السيارة'), ('in_progress', 'جاري تنفيذ الخدمة'), ('finished', 'اكتملت الخدمة'), ('cancelled', 'ملغي'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الموبايل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب العميل')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(verbose_name='التقييم (1-5)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='تعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.serviceorder', verbose_name='الطلب')),
            ],
        ),
        migrations.CreateModel(
            name='RejectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='سبب الرفض')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الرفض')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driver', verbose_name='السائق')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='accounts.serviceorder', verbose_name='الطلب')),
            ],
        ),
    ]
