# Generated by Django 6.0.4 on 2026-04-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='lat',
            field=models.FloatField(default=31.95, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='driver',
            name='lon',
            field=models.FloatField(default=35.91, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer_lat',
            field=models.FloatField(default=31.95),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer_lon',
            field=models.FloatField(default=35.91),
        ),
    ]
