# Generated by Django 5.2.13 on 2026-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver_lat_driver_lon_serviceorder_customer_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/ids/', verbose_name='صورة الهوية - الظهر'),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/ids/', verbose_name='صورة الهوية - الوجه'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق من الحساب'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/licenses/', verbose_name='رخة القيادة'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='appointment_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
