# Generated by Django 5.2.13 on 2026-05-01 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_driver_car_info_driver_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المستحق (د.أ)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('bank_account', models.CharField(blank=True, default='', max_length=200, verbose_name='رقم الحساب البنكي للإيداع')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_balance', to='accounts.driver', verbose_name='السائق')),
            ],
            options={
                'verbose_name': 'رصيد نقدي',
                'verbose_name_plural': 'الأرصدة النقدية',
            },
        ),
        migrations.CreateModel(
            name='CashSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المسوّى (د.أ)')),
                ('settled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسوية')),
                ('note', models.TextField(blank=True, default='', verbose_name='ملاحظة')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='accounts.driver', verbose_name='السائق')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_done', to=settings.AUTH_USER_MODEL, verbose_name='أجراها')),
            ],
            options={
                'verbose_name': 'تسوية نقدية',
                'verbose_name_plural': 'التسويات النقدية',
                'ordering': ['-settled_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي النقد (د.أ)')),
                ('qliq_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي QLIQ (د.أ)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='accounts.driver', verbose_name='السائق')),
            ],
            options={
                'verbose_name': 'تقرير يومي',
                'verbose_name_plural': 'التقارير اليومية',
                'ordering': ['-date', 'driver'],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
